# Generated by Django 4.0.5 on 2022-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_created=True, verbose_name='创建时间')),
                ('user_account', models.CharField(max_length=16, verbose_name='用户账号')),
                ('user_nick', models.CharField(max_length=32, verbose_name='用户昵称')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
            ],
        ),
    ]
