# Generated by Django 3.1.2 on 2022-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=16, verbose_name='用户账号')),
                ('user_password', models.CharField(default='', max_length=64, verbose_name='账号密码')),
                ('user_nick', models.CharField(max_length=32, verbose_name='用户昵称')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
            ],
        ),
    ]
