# Generated by Django 4.0.5 on 2022-06-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(default='2000-01-01', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=16, verbose_name='房间名称')),
                ('roomstatus', models.SmallIntegerField(choices=[(1, '空闲中'), (2, '游戏中'), (3, '结算中'), (4, '已关闭')], verbose_name='房间状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.userinfo', verbose_name='房主')),
            ],
        ),
    ]
