# Generated by Django 4.0.5 on 2022-06-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(default='', max_length=64, verbose_name='账号密码'),
        ),
    ]
