# Generated by Django 4.0.5 on 2022-07-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0002_alter_userinfo_birthday_alter_userinfo_id_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(choices=[(1, '东'), (2, '南'), (3, '西'), (4, '北')], verbose_name='方位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.userinfo', verbose_name='用户')),
            ],
        ),
    ]
