# Generated by Django 3.1.2 on 2022-07-02 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0003_roomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.CharField(max_length=32, verbose_name='游戏对局ID')),
                ('score_east', models.IntegerField(default=0, verbose_name='东方用户输赢积分')),
                ('score_south', models.IntegerField(default=0, verbose_name='男方用户输赢积分')),
                ('score_west', models.IntegerField(default=0, verbose_name='西方用户输赢积分')),
                ('score_north', models.IntegerField(default=0, verbose_name='北方用户输赢积分')),
                ('result_east', models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=0, verbose_name='东方用户游戏结果')),
                ('result_south', models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=0, verbose_name='南方用户游戏结果')),
                ('result_west', models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=0, verbose_name='西方用户游戏结果')),
                ('result_north', models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=0, verbose_name='北方用户游戏结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最近更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.room', verbose_name='房间')),
                ('user_east', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ue', to='scoreapp.userinfo', verbose_name='东方用户')),
                ('user_north', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_un', to='scoreapp.userinfo', verbose_name='北方用户')),
                ('user_south', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_us', to='scoreapp.userinfo', verbose_name='西方用户')),
                ('user_west', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_uw', to='scoreapp.userinfo', verbose_name='南方用户')),
            ],
        ),
    ]
