# Generated by Django 3.1.2 on 2022-07-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0005_auto_20220702_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='result_east',
            field=models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=-1, verbose_name='东方用户游戏结果'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='result_north',
            field=models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=-1, verbose_name='北方用户游戏结果'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='result_south',
            field=models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=-1, verbose_name='南方用户游戏结果'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='result_west',
            field=models.SmallIntegerField(choices=[(-1, '输'), (0, '平'), (1, '赢')], default=-1, verbose_name='西方用户游戏结果'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='score_east',
            field=models.IntegerField(default=0, verbose_name='东方用户输赢积分'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='score_north',
            field=models.IntegerField(default=0, verbose_name='北方用户输赢积分'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='score_south',
            field=models.IntegerField(default=0, verbose_name='男方用户输赢积分'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='score_west',
            field=models.IntegerField(default=0, verbose_name='西方用户输赢积分'),
        ),
    ]
