# Generated by Django 3.1.2 on 2022-07-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0006_auto_20220702_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='result_east',
            field=models.SmallIntegerField(choices=[(-1, '输'), (1, '赢')], default=-1, verbose_name='东方用户游戏结果'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='result_north',
            field=models.SmallIntegerField(choices=[(-1, '输'), (1, '赢')], default=-1, verbose_name='北方用户游戏结果'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='result_south',
            field=models.SmallIntegerField(choices=[(-1, '输'), (1, '赢')], default=-1, verbose_name='南方用户游戏结果'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='result_west',
            field=models.SmallIntegerField(choices=[(-1, '输'), (1, '赢')], default=-1, verbose_name='西方用户游戏结果'),
        ),
    ]
