# Generated by Django 3.1.2 on 2022-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0007_auto_20220702_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='record_type',
            field=models.SmallIntegerField(choices=[(1, '任意人添加'), (2, '赢家添加')], default=1, verbose_name='记录类型'),
        ),
    ]
