# Generated by Django 3.1.2 on 2022-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0008_gamerecord_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='record_status',
            field=models.SmallIntegerField(choices=[(1, '待确认'), (2, '已确认')], default=1, verbose_name='记录状态'),
        ),
    ]
